repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-coding==1.3.2
      - flake8-html==0.4.1
      - flake8-deprecated==1.3
      - flake8-todo==0.7
      - mccabe==0.6.1
